site_name: AGI Chaos
repo_url: https://github.com/yunwei37/My-AI-experiment
site_url: https://yunwei37.github.io/My-AI-experiment/
theme:
  name: material
  custom_dir: overrides
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - navigation.top
  theme:
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - search
  - social
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true
  - rss:
      match_path: ".*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  social:
  - icon: /fontawesome/regular/envelope
    name: send me an email
    link: mailto:yunwei37@gmail.com
hooks:
  - hooks/socialmedia.py
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
