name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material "mkdocs-material[imaging]" mkdocs-git-authors-plugin mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-rss-plugin
      - run: sudo apt-get install libcairo2-dev
      # New steps start here
      - name: Generate and update TOC
        run: |
          .github/replace.sh
      - name: Commit changes
        run: |
          git add README.md docs/index.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update table of contents" && git push)
      # New steps end here
      - run: mkdocs gh-deploy --force
