   name: Daily Publish

   on:
     schedule:
       # Runs at 00:30 UTC every day
       - cron: '10 07 * * *'

   jobs:
     publish:
       runs-on: ubuntu-latest
       permissions:
         # Give the default GITHUB_TOKEN write permission to commit and push the
         # added or changed files to the repository.
         contents: write
       steps:
       - uses: actions/checkout@v4
         with:
           recursive: true
       - name: submodule update
         run: |
          git submodule update --init --recursive
         
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
           python-version: '3.11'  # Specify your Python version

       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install python-dotenv requests

       - name: Run publish script
         env:
           PUBLISHER_API_KEY: ${{ secrets.PUBLISHER_API_KEY }}
           PUBLISH_AS_DRAFT: 'false'  # Or 'false' if you want to publish directly
         run: |
           python .github/manage/publish.py
       - name: Commit and Push Changes
         run: |
           git config --global user.email "yunwei356@gmail.com"
           git config --global user.name "yunwei37"
           git add .
           git diff --quiet && git diff --staged --quiet || (git commit -m "Update published" && git push)

